on: [push]

jobs:
  pwa_to_apk_job:
    runs-on: ubuntu-latest
    name: Test PWA to apk JOB
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone test repo
        run: git clone https://github.com/sharadcodes/pwa-to-apk-action-test && mv pwa-to-apk-action-test/* .
      - name: Test pwa-to-apk-action
        uses: ./
        with:
          project-root-folder: "."
          skip-signing: "false"
      - name: Test Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0
